board/urls.py
from board.views import *
from django.contrib import admin
from django.urls import path


app_name = 'board'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('list/',PostListView.as_view(),name='list'),
    path('<int:pk>/',PostDetailView.as_view(), name="detail"),
    path('add/', PostCreateView.as_view(), name="add"),
    path('<int:pk>/update/', PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),
    path('<int:pk>/comment/', comment_create,name="comment"),
    path('comment_delete/<int:pk>', CommentDeleteView.as_view(),name="comment_delete"),
    path('<int:pk>/like/',likes,name="like"),
]

sto/urls.py
from django.contrib import admin
from django.urls import path, include
from sto.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('donation/', include('donation.urls')),
    path('donationf/',include('donation.urls')),
    path('board/',include('board.urls')),
    path('funding/', include('funding.urls')),
]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 
from django.conf import settings
# Create your models here.

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, 
    help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    
    user = models.ForeignKey(User,on_delete=models.CASCADE,
        verbose_name='USER', blank=True, null=True)

    hits = models.PositiveIntegerField("조회수",default=0)

    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'board_posts'
        ordering = ('-create_dt',)
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:detail', args=(self.id,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self,*args,**kwargs):
        #필드 조정 필요시 작성
        super().save(*args,**kwargs)

    @property
    def hits_count(self):
        self.hits = self.hits + 1
        self.save()

class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE, null=True,
        related_name='comments')
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_contents = models.CharField(max_length=200)
    comment_writer= models.ForeignKey(User,on_delete=models.CASCADE, null=True)

    class Meta:
        ordering=['-id']

    def __str__(self):
        return self.comment_contents

board/views.py
from django.db import models
from django.http.response import HttpResponseRedirect
from board.models import Post, Comment
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.views import OwnerOnlyMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator 

class PostListView(ListView):
    model = Post
    template_name = 'board/post_list.html'
    context_object_name='posts'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        likes=[ post for post in Post.objects.all() if post.like.count() > 0 ]
        likes.sort(key=lambda p : p.like.count(), reverse=True)
        context['likes'] = likes[:5]
        
        return context


class PostDetailView(DetailView):
    model = Post
    

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'description', 'content']
    success_url = reverse_lazy('board:list')

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'description', 'content']
    success_url = reverse_lazy('board:list')

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('board:list')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)


def comment_create(request, pk):
    post_id = request.POST['post']
    content = request.POST['content']
    user = request.user

    post = Post.objects.get(pk=post_id)
    
    if content=='':
        return HttpResponseRedirect(reverse('board:detail', args=(post.id,)))
    else:
        comment = Comment(post=post, comment_contents = content, comment_writer=user)
        comment.save()
        # print('----- db 저장 ')
        # 리다이렉트 --> 
        return HttpResponseRedirect(reverse('board:detail', args=(post.id,)))

class CommentDeleteView(OwnerOnlyMixin, DeleteView):
    model = Comment
    # success_url  ---> 인자가 없는 경우 

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    # success_url을 동적으로 생성하는 경우 
    def get_success_url(self):
        postid = self.get_object().post.id

        return reverse_lazy('board:detail',args=(postid,))

# def comment_delete(request,pk):
#     comment= get_object_or_404(Post,id = pk)
#     post= get_object_or_404(Post,id = pk)
    
#     if request.method =='POST':
#         comment.delete()
#         return HttpResponseRedirect(reverse('board:detail', args=(post.id,)))


def likes(request,pk):
    post = get_object_or_404(Post, id=pk)
    if request.user in post.like.all():
        post.like.remove(request.user)
    else:
        post.like.add(request.user)

    return HttpResponseRedirect(reverse('board:detail', args=(post.id,)))




# class CommentCreateView(CreateView):
#     model = Comment
#     fields = ['post', 'content']

#     def form_valid(self):
#         print(self.form.instance)
#         pass

board/templates/board/post_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content-header %}
{% endblock %}

{% block content%}

<div class="container">

    <h1 style=" font-size:40px; font-weight: bold; margin-bottom: 0px;"><i class="fas fa-fish"></i> {{object.title}}
    </h1>

    <P style="font-size:13px; margin-top:2px; border-bottom: 1px solid black;">
    [작성일 : {{object.modify_dt|date:"Y-m-d"}}] [작성자 : {{user}}] [조회수 : {{object.hits}}]</P>
    <div>
        {% autoescape off %}
        {{ object.content }}
        {% endautoescape%}
    </div>

    {% comment %} <p>
        {%if object.get_previous %}
        <a href="{{object.get_previous.get_absolute_url}}" title="이전 글">prev</a>
        {%endif%}
        {%if object.get_next %}
        <a href="{{object.get_next.get_absolute_url}}" title="다음 글">next</a>
        {%endif%}
    </p> {% endcomment %}
    
    <div class="text-right">
        {% if user.is_active %}
            {% if user in post.like.all %}
                <a href="{% url 'board:like' post.id %}">
                <i class="fas fa-heart" style="color:red;"></i></a>
            {% else %}
                <a href="{% url 'board:like' post.id %}">
                <i class="far fa-heart"></i></a>
            {% endif %}
            {{post.like.count}}
        {% else %}
            <i class="far fa-heart mr-2"></i><span style="font-size:20px; margin-left:8px">{{post.like.count}}</span>
        {% endif %}
        
        
        {% if user == post.user %}
        <a href="{% url 'board:update' post.id %}" class="mr-3 ml-3">
            <i class="far fa-edit"></i> 수정</a>
        <a href="javascript:deletePost('{% url 'board:delete' post.id %}')" class="text-danger mr-3"><i
                class="fas fa-trash"></i> 삭제</a>
        {% endif %}
    </div>
    <br>

    <form action="{% url 'board:comment' post.pk %}" method="POST" id="f1" >
        {%csrf_token%}
        <input type="hidden" name="post" value="{{post.pk}}">
        <input type="text" name="content" placeholder="Write your comments">
        {% if user.is_active %}
            <input class ="cmt"type="submit" value="Write"/>
        {% else %}
            <a href="{% url 'login' %}" class="button  smooth-scroll-middle">Write</a>
        {% endif %}
            
    </form>
    {% if user == post.user %}
    
    {% endif %}
    {% for comment in post.comments.all %}
        <div class="comment">
            <div class="date">{{comment.comment_date}}</div>
            <p style="margin-bottom:0px">작성자 : {{comment.comment_writer}}</p>
            <p style="margin-bottom:0px">{{comment.comment_contents}}</p>
            {% if user == comment.comment_writer %}
                <a href="javascript:deletePost('{% url 'board:comment_delete' comment.id %}')" class="text-danger mr-3"><i
                class="fas fa-trash"></i> 삭제</a>
            {% endif %}
        </div>
        <br>
    
    {%empty%}
        <p>No comment</p>
    {% endfor %}


</div>



{% endblock %}

{% block script %}
<script>
    function deletePost(url) {
        if (!confirm('삭제할까요?')) {
            return
        }
        location = url
    }
</script>

<script>
    {{post.hits_count}}
</script>


{% endblock %}

board/templates/board/post_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content-haeder %}
    <h1><i class="nav-icon fas fa-blog"></i> Post 생성/수정 - {{user}}</h1>
{% endblock %}

{% block content %}
    <div>
        <form action='.' method="post" class="form col-sm-8 mx-auto">
            {% csrf_token %}
            {%bootstrap_form form%}
            
            <a type="submit" class="btn btn-primary">
                <i class="fas fa-check"></i> 확인
            </a>
            <a href="javascript:history.back()" class="btn btn-primary">
                <i class="fas fa-undo"></i> 취소
            
            </a>
        </form>
    </div>

    {% load static %} 
    {% block style %}
        <link rel="stylesheet" 
            href="{% static 'plugins/summernote/summernote-bs4.min.css' %}"> 
    {% endblock %}

    {% block script %}
        <script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"> 
        </script>
    <script>
    $(function () {
        // Summernote 
        $('#id_content').summernote({
            height: 300 
        }) 
    }) 
    </script>
    {% endblock%}

{% endblock%}

board/templates/board/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content-header %}  
<h2 style ="font-weight:bold; margin-top:10px; margin-bottom:5px; margin-left:30px">자유게시판</h2>
{% endblock %} 

{% block content %}
    <br>
    <div class="container">
        <div class="row">
            <div class ="col-md-9">
                <table class="table-striped table-hover" >
                    <thead>
                        <tr>
                            <th style="width:20px">No</th>
                            <th style="padding-top:10px " >제목</th>
                            <th style="width:120px" class="text-center">글쓴이</th>
                            <th style="width:120px" class="text-center">등록일</th>
                            <th style="width:80px" class="text-center">조회수</th>
                            <th style="width:80px" class="text-center">추천</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for writing in posts%}
                        <tr  style="cursor:pointer;" onclick="location.href='{{writing.get_absolute_url}}'">
                            <td>{{writing.id}}</td>
                            <td style="white-space:nowrap; overflow:hidden;text-overflow:ellipsis;">{{writing.title}}</td>
                            <td class="text-center">{{writing.user}}</td>
                            <td class="text-center">{{writing.create_dt|date:"Y-m-d"}}</td>
                            <td class="text-center">{{writing.hits}}</td>
                            <td class="text-center">{{writing.like.count}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div style="width:400px; margin-left:auto; margin-right:auto;">
                    {% bootstrap_pagination page_obj pages_to_show='5'%}
                </div>
                {% comment %} 
                    <ul class="pagination pagination-sm justify-content-center" style="margin-bottom:0px">
                    <li class="page-item"><a class="page-link" href="?page=1"><i class="fas fa-angle-double-left"></i></a>
                    </li>
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_num >= page_obj.number|add:-2 and page_num <= page_obj.number|add:2 %}
                            <li class="page-item"><a class="page-link" href="?page={{page_num}}">{{page_num}}</a></li>
                        {%endif%}
                    {% endfor %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.paginator.num_pages}}"><i class="fas fa-angle-double-right"></i></a>
                    </li>
                </ul>  
                {% endcomment %}
            
                <div class="text-right" style="margin-bottom:30px;margin-top:0px">
                    <a href="{%url 'board:add' %}" class="btn btn-primary btn-sm ">
                    <i class="fas fa-pencil-alt"></i> 쓰기</a>
                </div>
            </div>
            <div class="col-md-3">
                <h5 style="font-weight:bold; color: firebrick;"><i class="fab fa-hotjar"></i> 인기 글</h5>
                <ol>
                    <!-- 검색순위 나열 -->
                    {% for i in likes%}
                        <li>
                            <div title="{{i.title}}" onMouseOver="this.style.color='red'" onMouseOut="this.style.color='black'"
                            style="cursor:pointer; width:150px; white-space:nowrap; overflow:hidden;text-overflow:ellipsis;" onclick="location.href='{{i.get_absolute_url}}'">
                                {{i.title}}
                            </div>
                        </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
        
        
{% endblock %}