donation/urls.py
from django.urls import path
from donation.views import *

app_name = 'donation'

urlpatterns = [
    path('',PersonListView.as_view(),name ='index'),
    path('donationC/',DonationCreateView.as_view(), name= 'donation_check'),
    path('donationF/<int:pk>',FinalDetailView.as_view(), name='donation_fin'),
    path('newsletter/',NewsLetterView.as_view(),name ='newsletter'),
    path('intro/',IntroView.as_view(),name='intro'),
    path('campaign/',CampaignView.as_view(),name='campaign'),
]

sto/urls.py
from django.contrib import admin
from django.urls import path, include
from sto.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('donation/', include('donation.urls')),
    path('donationf/',include('donation.urls')),
    path('board/',include('board.urls')),
    path('funding/', include('funding.urls')),
]

donation/models.py
from django.db import models
from django.contrib.auth.models import User

class Donation(models.Model):
    choice_card = { 
        ('shinhan', '신한'),
        ('woori', '우리'),
        ('hana', '하나'),
        ('kB', '국민'),
    }   


    user = models.ForeignKey(User,on_delete=models.CASCADE, blank=True, null=True )
    amount = models.IntegerField("금액",default=0)
    card = models.CharField("카드사", max_length=10, choices = choice_card)
    card_num = models.IntegerField("카드번호",default=0)
    create_dt = models.DateField('CREATE DATE', auto_now_add=True,null=True, blank=True)
    def __str__(self):
        return str(self.user)

donation/views.py
from django.shortcuts import render
from django.utils.translation import templatize
from django.views.generic import CreateView, ListView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from donation.models import Donation
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class PersonListView(TemplateView):
    template_name = 'donation/donation_amount.html'

# CreateView
class DonationCreateView(CreateView):
    model = Donation
    fields = ['amount','card','card_num']
    # success_url = reverse_lazy('donation:donation_fin')

    def form_valid(self, form):
        form.instance.user = self.request.user
        # print(self.request.user, self.request.user.id)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('donation:donation_fin', args=(self.object.id, ))

class FinalDetailView(DetailView):
    model = Donation
    template_name = 'donation/End.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # context['object']
        # 총 후원금을 계산
        total = 0
        rows = Donation.objects.filter(user=self.request.user)
        for i in rows:
            total += i.amount
        context['total'] = total
        return context

class NewsLetterView(TemplateView):
    template_name = 'donation/newsletter.html'

class IntroView(TemplateView):
    template_name = 'donation/intro.html'

class CampaignView(TemplateView):
    template_name = 'donation/campaign.html'

donation/templates/donation/End.html
{% extends 'base.html' %}

<!doctype html>
<html lang="en">

{% block content %}

<head>
  <title>후원완료창</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <style>
    p.c1 {
      display: block;
      margin: 0;
      width: 100%;
      line-height: 120%;
      padding: 24px 0;
      border-color: #aa9696;
      border-width: 1px 0;
      border-style: solid;
      color: #000000;
      text-align: center;
    }
  </style>


</head>

<body>
  <div class ="text-center">
    <br>
    <h3>{{user}} 후원자님의 후원내역</h3>
    <br><br>
      {{user}} 후원자님, 후원에 감사드립니다.
      </br><br>
      후원금은 10일에 결제되며, 미결제시 27일 재결제 됩니다.
  </div>
  <br><br><br>
  <div class="container text-center">
    <div class="row">
      {% comment %} <div class="com-md-2">
      </div> {% endcomment %}
          <div class="col-md-3 font-weight-bold">
            
            <p><i class="far fa-calendar-check"></i></p>
            <p>후원시작일</p>
            <p>{{object.create_dt|date:"Y-m-d"}}</p>
          </div>

          <div class="col-md-3 font-weight-bold">
            <p><i class="far fa-money-bill-alt"></i></p>
            <p>후원내용</p>
            <p>{{object.amount}}</p>
          </div>

          <div class="col-md-3 font-weight-bold">
            <p><i class="fas fa-credit-card"></i></p>
            <p>납부방법</p>
            <p>{{object.get_card_display}}</p>
          </div>

          <div class="col-md-3 font-weight-bold">
            <p><i class="fas fa-credit-card"></i></p>
            <p>총 납부금액</p>
            <p>{{total}}</p>
          </div>

        </div> 
      </div>
    </div>
  </div>
  <br><br>
  <div class="container">
    <p class="c1">
      멀티캠퍼스 1조는 캠페인의 정치적, 재정적 독립성을 유지하기 위해 정부와 기업의 후원을 일체 받지 않으며<br> 
      개인 후원자님들의 후원으로만 활동하고 있습니다.<br><br>
      바로 여러분의 후원이 있기에 지구를 위한 긍정적인 
      변화를 만들 수 있습니다. <br><br>
      함께 변화를 만들어 주셔서 감사합니다!  
    </p>
  </div>



  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</body>

</html>

{% endblock%}

donation/templates/donation/campaign.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="ko">
  <head>
    <title>캠페인</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {%block style%}
    <style>
        .achieve{             
            border-top: 2px solid gray;
            text-align : center;
        }
        .article > div{
            border: 2px solid black;
            width: 50%;
            height: 10%;
            
        }
        .article> div> a{
            margin-top: 2%;
            margin-bottom: 2%;
        }
      
    </style> 
    {%endblock%}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block content-header%}
    <h1 class="text-center" style="font-weight: bold; font-size : 40px;">[  멀티캠퍼스 캠페인  ]</h1><br>
    <p class="text-center" style="font-size: 25px; margin-bottom:5px;">" 멀티캠퍼스에서 진행하는 <i><b><ins>지역 및 글로벌 캠페인</ins></b></i> &nbsp에 대해 자세히 알아보세요." </p>
    {%endblock%}
</head>
  <body>
    {% block content %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card" style="width:100%">
                    <img class="card-img-top" src="{% static 'images/플라스틱.jpg' %}" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title"><b>플라스틱 프리챌린지</b></h4>
                        <p class="card-text">플라스틱 줄이는 환경운동 캠페인</p>
                        <a href="http://apnews.kr/View.aspx?No=827174" class="btn btn-primary">더 알아보기</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card" style="width:100%">
                    <img class="card-img-top" src="{% static 'images/플라스틱2.jpg' %}" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title"><b>플로깅</b></h4>
                        <p class="card-text">지구를 살리는 아름다운 달리기</p>
                        <a href="https://biz.chosun.com/topics/topics_social/2021/05/04/JFLJLWXMZBFRNCKLQDXT3KGXJQ/" class="btn btn-primary">더 알아보기</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card" style="width:100%;">
                    <img class="card-img-top" src="{% static 'images/바다.jpg' %}" alt="Card image" style="height:auto;">
                    <div class="card-body">
                        <h4 class="card-title"><b>海치우자!</b></h4>
                        <p class="card-text">바다를 지키기 위한 9가지 약속</p>
                        <a href="https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=koreamof&logNo=220772054847" class="btn btn-primary">더 알아보기</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>

    <div class="achieve">
        <h2 style="font-size:40px; font-weight:bold; margin-top:40px;">[  캠페인 성과  ]</h2>
        <p></p>
        <h3 style="font-size:30px; font-weight:bold">" 함께라면 우리는 더 큰 변화를 만들 수 있습니다. "</h3>
        <p></p>
    </div>
    <div class="container" >
        <div class = 'row'>
            <div class="col-md-4" style="border-right: 1px solid lightgrey; cursor:pointer;", onclick="location.href='https://www.greenpeace.org/korea/update/18201/blog-ce-naver-re100-roadmap/'">
                <img src="{% static 'images/b.jpg' %}" style=" float:right; margin-top:40px; margin-left:20px;margin-right:20px; margin-bottom:20px;box-shadow: 5px;">
                <span style="font-size:13px; color:yellow; text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">기후</span>
                <span style="font-size:13px;">최신이야기</span>
                <h4 style="font-weight:bold;">네이버의 100% 재생에너지 로드맵 발표의 의미와 과제 </h4>
                <p style="font-size:13px;">2021년 07월 01일</p>
            </div>

            <div class="col-md-4" style="border-right: 1px solid lightgrey; cursor:pointer;", onclick="location.href='{% url 'donation:newsletter' %}'">
                <img src="{% static 'images/c.jpg' %}" style=" float:right; margin-top:40px; margin-left:20px;margin-right:20px; margin-bottom:20px;box-shadow: 5px;">
                <span style="font-size:13px; color:blue; text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">해양</span>
                <span style="font-size:13px;">최신이야기</span>
                <h4 style="font-weight:bold;">한국 정부, 공해상 30X30 해양보호구역 지지 선언! </h4>
                <p style="font-size:13px;">2021년 06월 01일</p>
            </div>

            <div class="col-md-4", style=" cursor:pointer;" onclick="location.href='https://www.greenpeace.org/korea/update/17518/blog-plastic-7-eleven-taiwan-announces-phase-out-of-single-use-plastics-a-first-in-asia/'">
                <img src="{% static 'images/d.jpg' %}" style=" float:right; margin-top:40px; margin-left:20px;margin-right:20px; margin-bottom:20px;box-shadow: 5px;">
                <span style="font-size:13px; color:gray; text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">플라스틱</span>
                <span style="font-size:13px;">최신이야기</span>
                <h4 style="font-weight:bold;">대만 세븐일레븐 편의점에서 앞으로 OOOO을 볼 수 없다? </h4>
                <p style="font-size:13px;">2021년 05월 11일</p>
            </div>
        </div>
    </div>
    <br>
    
    <div class="container">
        <div class = 'row'>
            <div class="col-md-4" style="border-right: 1px solid lightgrey;  cursor:pointer;", onclick="location.href='https://www.greenpeace.org/korea/update/17352/blog-etc-independent/'">
                <img src="{% static 'images/e.jpg' %}" style=" float:right; margin-top:40px; margin-left:20px;margin-right:20px; margin-bottom:20px;box-shadow: 5px;">
                <span style="font-size:13px; color:yellow; text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">기후</span>
                <span style="font-size:13px;">최신이야기</span>
                <h4 style="font-weight:bold;">멀티캠퍼스를 유지할 수 있었던 힘 '독립성'</h4>
                <p style="font-size:13px;">2021년 04월 20일</p>
            </div>

            <div class="col-md-4" style="border-right: 1px solid lightgrey;  cursor:pointer;", onclick="location.href='https://www.greenpeace.org/korea/update/16788/blog-etc-2021-globalvictory/'">
                <img src="{% static 'images/f.jpg' %}" style=" float:right; margin-top:40px; margin-left:20px;margin-right:20px; margin-bottom:20px;box-shadow: 5px;">
                <span style="font-size:13px;">최신이야기</span>
                <h4 style="font-weight:bold;">2021, 지구를 위한 즐거운 변화들을 소개합니다 </h4>
                <p style="font-size:13px;">2021년 03월 03일</p>
            </div>

            <div class="col-md-4", style="cursor:pointer;", onclick="location.href='https://www.greenpeace.org/korea/update/16788/blog-etc-2021-globalvictory/'">
                <img src="{% static 'images/a.jpg' %}" style=" float:right; margin-top:40px; margin-left:20px;margin-right:20px; margin-bottom:20px;box-shadow: 5px;">
                <span style="font-size:13px; color:yellow; text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">기후</span>
                <span style="font-size:13px;">최신이야기</span>
                <h4 style="font-weight:bold;">[카드뉴스] 어스앤런 버추얼 달리기로 우리가 만들어낸 변화 </h4>
                <p style="font-size:13px;">2021년 01월 22일</p>
            </div>
        </div>
    </div>


    <!-- <div class="container">
       
            <div class="article">
                <div class="mx-auto">
                    <a href="{% url 'donation:newsletter' %}"><p>한국 정부, 공해상 30x30 해양보호구역 지지 선언</p></a>
                </div>
                <br>
                <div class="mx-auto" style="cursor:pointer" onclick="location.href='https://www.naver.com'">
                    <p>대만 세븐 일레븐, 더이상 ㅇㅇㅇㅇ을 볼 수 없다.</p>
                </div>
                <br>
                <div class="mx-auto">
                    <P>2021 지구를 위한 즐거운 변화들을 소개합니다.</P>
                </div>
                </div>
            </div>
        </div>
    </div> -->

    
    {% endblock%}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>
    

donation/templates/donation/donation_form.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content-header %}
    
{% endblock %}

{% block style%}
    <style>
        #ContentMessage {
            position: relative;
            top: -60px;
            padding: 20px 60px 10px;
            background-color: #80c342;
            

            width : 90%;
            margin-left: 40px;
        }

        .content-home__title{
            color: #fff;
            font-weight: 1000;
        }

        .content-message__title {
            display: block;
            margin: 0;
            width: 100%;
            line-height: 120%;
            padding: 24px 0;
            border-color: #80c342;
            border-width: 1px 0;
            border-style: solid;
            color: #80c342;
            text-align: center;
        }
    </style>
{% endblock%}


{% block content %}

<div class="row mt-3">
    <!-- mt-3 : 마진 탑 간격 3/ 3이 글자 한개 크기-->
    <!-- 좌측 화면 -->
    <div class="col-md-7">
        <div class="row">
            <div class="image">                        
            <img class=" img-fluid"  src="{% static 'images/거북이.jpg' %}" alt="" />
            </div>
        </div>
        <br>
        {% comment %} 컨텐트 메시지 스타일 {% endcomment %}
        

        <div id = "ContentMessage" class="wide img-fluid">
            <h2 class="content-home__title">
                당신의 후원이 변화를 만듭니다
            </h2>
        </div>
         <div>
        <h2 class="content-message__title">우리의 지구를 함께 지켜주세요</h1>
        <div class="content-message__text text-center" >
        "지구는 동시다발적인 환경문제로 심각한 위기에 처해있습니다. 
        <br>하지만 우리에게는 아직 기회가 있습니다."
        <br>
        <br>
        "환경문제 해결을 위해서는 한시라도 빨리 행동해야 합니다."
        <br>
        <br>
        "여러분의 후원으로 환경 문제를 조사하고, 경각심을 불러 일으키는 보고서를 발표하고,<br>
        창의적인 캠페인과 직접 행동을 펼칠 수 있습니다.<br>
        미래 세대가 깨끗한 세상에서 살 수 있도록, 지구를 위한 변화를 함께 만들어주세요!"
        </div>
    </div>
    </div> <!-- 좌측 메인컨텐츠 끝-->

    <div class="col-md-5" style="border-left: 1px solid lightgrey;">
        <!-- 우측메뉴 시작 -->
        <div class="text-center ">
        {% comment %} <style>
            #id_card { width:300px;}
        </style>  {% endcomment %}
            <br>
            <h2>체크카드와 신용카드 <br>모두 가능합니다.</h2>
            <p>첫 후원금은 10일 혹은 27일에 결제 됩니다. </br>
                익월 부터는 정기결제일인 10일에 결제되며,<br> 미결제시 27일 재결제 됩니다.</p>
        </div>
        <div class= "">
                <form action="." method="post" class="form col-sm-10 mx-auto">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button  onclick="javascript:history.back()" class="btn float-right btn-sm">
                        <i class="fas fa-undo"></i> 취소
                    </button>
                    <button type="submit" class="btn float-right btn-sm">
                            <i class="fas fa-sign-in-alt"></i> 확인</button>
                    </button>

                </form>
            </div>
    </div> <!-- 우측메뉴 끝-->
</div>







{% endblock %}