funding/urls.py
from django.urls import path
from funding.views import *

app_name = 'funding'

urlpatterns = [
    path('',FundingTemplateView.as_view(),name ='index'),
    path('list/',FundingListView.as_view(),name ='funding'),
    path('<int:pk>/',FundingDetailView.as_view(),name ='funding_detail'),
    path('add/',FundingCreateView.as_view(),name ='create'),
    path('like/<int:pk>',likes,name="like"),
]

sto/urls.py
from django.contrib import admin
from django.urls import path, include
from sto.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('donation/', include('donation.urls')),
    path('donationf/',include('donation.urls')),
    path('board/',include('board.urls')),
    path('funding/', include('funding.urls')),
]

funding/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime 
from django.conf import settings
# Create your models here.

class FundingInfo(models.Model):
    # 마감날짜, 목표금액, 서포터????, 
    title = models.CharField(max_length=200)
    end_date = models.DateTimeField(blank=True, null=True)
    goal_price = models.IntegerField(default=0)
    price = models.IntegerField(default=0)

    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_funding", blank=True)
    
    def __str__(self):
        return self.title

#  1000 x 100(%)
# 10000 
class Funding(models.Model):
    choice_card = { 
        ('shinhan', '신한'),
        ('woori', '우리'),
        ('hana', '하나'),
        ('kB', '국민'),
    }   
    choice_color = { 
        ('nougat', 'nougat 누가'),
        ('stormy', 'stormy 스토미'),
        ('pompom', 'pompom 폼폼'),
        ('milk', 'milk 밀크'),
    }

    user = models.ForeignKey(User,on_delete=models.CASCADE,
        verbose_name='USER', blank=True, null=True)
    funding_info = models.ForeignKey(FundingInfo,on_delete=models.CASCADE,
        verbose_name='Funding Info.', blank=True, null=True)
    cash = models.IntegerField(default=0)
    card = models.CharField("카드사", max_length=10, choices = choice_card, default='')
    card_num = models.IntegerField("카드번호",default=0)
    create_dt = models.DateField('CREATE DATE', auto_now_add=True,null=True, blank=True)
    color =models.CharField("색상", max_length=10, choices = choice_color, default='')
    
    class Meta:
        ordering = ('-cash',)
    # def get_absolute_url(self):
    #     return reverse('funding:funding_detail', args=(self.id,))

funding/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from funding.models import Funding, FundingInfo
from datetime import datetime
from django.urls import reverse_lazy
from django.http.response import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

class FundingTemplateView(TemplateView):
    model = FundingInfo
    template_name="funding/funding_index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fi = FundingInfo.objects.get(pk=3)
        context["object"] = fi
        context["remaining"] = fi.end_date - datetime.now()  # timedelta

        fundings = Funding.objects.filter(funding_info=fi)
        total = 0
        count=0
        for f in fundings:
            total += f.cash
            count += 1
    
        context["total"] = total
        context["rate"] = int(total / fi.goal_price * 100)
        context["count"] = count
        return context

class FundingListView(ListView):
    model = Funding
    template_name = 'funding/funding_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fi = FundingInfo.objects.get(pk=3)
        context["object"] = fi
        context["remaining"] = fi.end_date - datetime.now()  # timedelta

        fundings = Funding.objects.filter(funding_info=fi)
        total = 0
        count=0
        for f in fundings:
            total += f.cash
            count += 1
    
        context["total"] = total
        context["rate"] = int(total / fi.goal_price * 100)
        context["count"] = count
        return context

class FundingDetailView(DetailView):
    model = Funding


class FundingCreateView(CreateView):
    model = Funding
    fields = ['cash','funding_info', 'card','card_num','color']
    success_url = reverse_lazy('funding:funding')

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)


def likes(request,pk):
    post = get_object_or_404(FundingInfo, id=pk)
    if request.user in post.like.all():
        post.like.remove(request.user)
    else:
        post.like.add(request.user)

    return HttpResponseRedirect(reverse('funding:funding'))

   
# def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         funding = context["object"]

#         context["remaining"] = funding.end_date - datetime.now()  # timedelta
#         print(context["remaining"])
#         return context

funding/templates/funding/common.html
{% load static %}

            <h3 class="text-center mt-5 mb-0"><b>"사람 한 명당 연평균 <i><ins><span style="background-color: #FFFF00">84kg의 플라스틱 </span></ins></i> 폐기물을 <br>만듭니다."</b></h3>
            <div class="image mt-0">                        
                <img src="{% static 'images/펀딩_1.jpg' %}" alt="" />
            </div>
            <div style="line-height:40px; font-size:16px">
            알고 계신가요?<br>
            플라스틱은 썩지 않고 분해되지 않는 특성으로 가장 큰 문제가 생태계교란이라는 사실!<br>
            플라스틱은 미생물에 의해 분해되지는 않지만, 오랜 세월 바다에서 떠돌며 햇빛에 노출되면 물리적 충격에 의해 잘게 부스러지기 마련입니다. 이렇게 잘게 부스러진 마이크로플라스틱은 많은 해양 생물들에게 먹잇감으로 오인되곤 합니다.<br>
            물속의 플랑크톤이나 작은 갑각류를 걸러 먹는 것은 많은 물고기들의 영양 섭취 방법입니다. 마이크로플라스틱을 먹이로 오인해 섭취하는 경우 이들은 소화되지 않고 몸속에 그대로 쌓이게 되고, 이들은 다시 먹이사슬을 따라 상위 단계의 포식자들에게 먹힘으로써 결국 생태계 전반으로 퍼져나갑니다.<br>
            즉,<span style="border-bottom: 2px solid #00cca3;"><strong>내부로부터의 ‘플라스틱 중독’이 일어나  해양 생태계에 치명적인 영향을 미치게 될 것입니다.</strong></span> 지구 표면의 70%를 차지하는 해양 생태계가 교란되면 그 영향은 결국 <span style="border-bottom: 2px solid #00cca3;"><strong>전 지구적으로 확산되어 우리 역시도 그 파멸의 소용돌이에서 자유로울 수 없습니다.</strong></span> 지금 이 시간도 북태평양 바다 위에는 또 하나의 플라스틱 더미가 늘어나고 있을 것입니다. 우리가 쉽게 사용하고 버리는 플라스틱 제품들이 그 속도를 더욱 가속화 시킬지도 모릅니다.<br>
            </div>
            <div style="margin-bottom:30px"><img src="{% static 'images/보틀1.jpg' %}" alt=""/></div>
            <div><img src="{% static 'images/보틀2.jpg' %}" alt=""/></div>
            <div class="mt-3 mb-4 ml-3"><img src="{% static 'images/보틀3.jpg' %}" alt=""/></div>
        
            <div>
                <h3><b>| 도서/산간 추가 배송비 안내</b></h3>
                <p style="font-size:16px;">리워드설계에서 제주/도서간 추가배송비를 꼭 지불해 주셔야 발송이 됩니다.</P>
                <br>
                <h3><b>| 발송안내 </b> </h3>
                
                <ul style="font-size:16px">
                    <li>리워드는 CJ대한통운을 통해 발송됩니다.</li>
                    <li>제품 발송은 10월 말일일 부터(21일~29일) 순차적 발송(일일 최대 1,000대)을 계획하고 있으며, 배송 소식은 새소식을 통해 내용 공유해 드리겠습니다.</li>
                    <li>제품 발송일로 부터 택배사에 따라 2~3일 이내 수령이 가능합니다.</li>
                    <li>발송 문의는 메이커에게 문의하기/ 댓글을 이용하시면 편리합니다.</li>
                    <li>리워드 및 배송 문의 : ㈜아이엠무역 고객센터 070-7706-2579</li>
                    <li>카카오톡 플러스 친구 @아이엠키친 : http://pf.kakao.com/_vQZtK</li>
                    <li>결제 관련 문의 : 최종 결제일인  9월 5일  일요일까지 와디즈 고객센터 1661-9056 로 연락 주세요.</li>
                </ul>
            </div>

funding/templates/funding/funding_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content-header %}
    <h3 class="text-center mt-2 mb-0"><b>[플라스틱과 맞바꾼 텀블러]오늘도, 내일도 환경을 생각하는 #원그린보틀</b></h3>
{% endblock%}

{% block content %}
<div class="container">
    <div class="row mt-3">
        <!-- 좌측 화면 -->
        <div class="col-md-7">
            {% include './common.html' %}
        </div>
        
        <!-- 우측 화면-->
        <div class="col-md-5">
            <div>
                <h2>{{object.title}}</h2>
                <div style="border-bottom: 2px solid #00cca3;"><h3>{{remaining.days}}일 남음</h3></div>
                <div>{{rate}}% 달성</div>
                <div>{{total}}원 펀딩</div>
                <div>{{count}}명의 서포터</div>
            </div>
            <button style=" background-color:#00cca3; text-align:center;cursor:pointer;">펀딩하기</button>
            <div class="row">
                <div class="col-md-4"><i class="far fa-heart"></i> 48</div>
                <div class="col-md-4">문의</div>
                <div class="col-md-4">공유하기</div>
            </div>
            <div>
                <h2>체크카드와 신용카드 <br>모두 가능합니다.</h2>
            </div>
            

        </div>

    </div>
</div>
{% endblock  %}

{% block script %}
<script>

</script>
{% endblock script %}

funding/templates/funding/funding_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content-header %}
    <h3 class="text-center mt-2 mb-0"><b>[플라스틱과 맞바꾼 텀블러]오늘도, 내일도 환경을 생각하는 #원그린보틀</b></h3>
{% endblock%}

{% block content %}
<div class="container">
    <div class="row mt-3">
        <!-- 좌측 화면 -->
        <div class="col-md-7">
            {% include './common.html' %}
        </div>
        
        <!-- 우측 화면-->
        <div class="col-md-5">
            <div style="border-bottom: 2px solid #00cca3; margin-top:76px;margin-bottom:30px">
                <h3>리워드 선택</h3>
            </div>
            
            <div class= "">
                <form action="." method="post" class="form col-sm-10 mx-auto">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button  onclick="javascript:history.back()" class="btn float-right btn-sm">
                        <i class="fas fa-undo"></i> 취소
                    </button>
                    <button type="submit" class="btn float-right btn-sm">
                            <i class="fas fa-sign-in-alt"></i> 확인</button>
                    </button>
                </form>
            </div>
        </div>

    </div>
</div>
{% endblock  %}

funding/templates/funding/funding_index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content-header %}
    <h3 class="text-center mt-2 mb-0"><b>[플라스틱과 맞바꾼 텀블러]오늘도, 내일도 환경을 생각하는 #원그린보틀</b></h3>
{% endblock%}

{% block content %}
<div class="container">
    <div class="row mt-3">
        <!-- 좌측 화면 -->
        <div class="col-md-7">
            {% include './common.html' %}
        </div>
        
        <!-- 우측 화면-->
        <div class="col-md-5">
            <div>
                <h2>{{object.title}}</h2>
                <div style="border-bottom: 2px solid #00cca3;"><h3>{{remaining.days}}일 남음</h3></div>
                <div>{{rate}}% 달성</div>
                <div>{{total}}원 펀딩</div>
                <div>{{count}}명의 서포터</div>
                
            </div>
             
            <a class="button big wide smooth-scroll-middle" href="{%url 'funding:funding' %}"
                style="background-color:#00cca3; text-align:center; cursor:pointer;">펀딩하기</a>
            <div class="row">
                <div class="col-md-4"><i class="far fa-heart"></i> 48</div>
                <div class="col-md-4">문의</div>
                <div class="col-md-4">공유하기</div>
            </div>
            
        </div>

    </div>
</div>
{% endblock  %}

funding/templates/funding/funding_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content-header %}
    <h3 class="text-center mt-2 mb-0"><b>[플라스틱과 맞바꾼 텀블러]오늘도, 내일도 환경을 생각하는 #원그린보틀</b></h3>
{% endblock%}

{% block content %}
<div class="container">
    <div class="row mt-3">
        <!-- 좌측 화면 -->
        <div class="col-md-7">
            {% include './common.html' %}
        </div>
        
        <!-- 우측 화면-->
        <div class="col-md-5">
            <!--펀딩 정보-->
            <div>
                <div style="border-bottom: 2px solid #00cca3;margin-top:56px">
                    <h2 class="mb-0">{{remaining.days}}일 남음</h2>
                        <span style="font-size:15px;">
                            __이 펀딩이 좋으시다면 하트를 눌러주세요!
                            {% if user.is_active %}
                                {% if user in object.like.all %}
                                    <a href="{% url 'funding:like' object.id %}" >
                                    <i class="fas fa-heart ml-2" style="color:red;"></i></a>
                                {% else %}
                                    <a href="{% url 'funding:like' object.id %}" >
                                    <i class="far fa-heart ml-2"></i></a>
                                {% endif %}
                                &nbsp{{object.like.count}}
                            {% else %}
                                <i class="far fa-heart ml-2 mr-1"></i>{{object.like.count}}
                            {% endif %}
                        </span>
                    
                </div>
                <div class="mt-2 mb-2" style="font-size:30px">{{rate}}% 달성</div>
                <div class="mt-2 mb-2" style="font-size:30px">{{total}}원 펀딩</div>
                <div class="mt-2 mb-2" style="font-size:30px">{{count}}명의 서포터</div>
            </div>
            {% if user.is_active %}
                <a class="button big wide smooth-scroll-middle mt-3 mb-3"
                    style="margin-left:30px; width:100%; background-color:#00cca3; text-align:center;cursor:pointer; "
                    href="{% url 'funding:create' %}">펀딩하기</a>
            {% else %}
                <a class="button big wide smooth-scroll-middle mt-3 mb-3"
                    style="margin-left:30px; width:100%; background-color:#00cca3; text-align:center;cursor:pointer; "
                    href="{% url 'login' %}">펀딩하기</a>

            {% endif %}

            

            <div>
                <ul class="mt-3">
                    <b style="background-color: #FFFF00">**READ ME@: 펀딩하기 전에 꼭 한번 읽어주세요!**</b>
                    <li class="mt-2">[리워드형] 제품가격은 {{object.price}}원입니다. 따라서 {{object.price}}원~30000원 미만 펀딩 시 제품 1개를 받아보실 수 있고, 30000~45000원 미만 제품 2개 받아보실 수 있습니다. 1인당 주문 가능한 수량은 최대2개입니다.</li>
                    <li class="mt-2">[후원형] 제품 가격 {{object.price}}보다 낮은 금액을 펀딩하실 경우, 단순 후원으로 처리가 됩니다. </li>
                    <li class="mt-2">위 두가지 펀딩 유형의 차이점을 숙지하시고, 펀딩에 참여해주시길 바랍니다. 건강한 지구를 위해 함께 해주시는 모든 여러분들께 감사의 말씀드리며, 궁금하신 사항은 언제든 010-1234-1234로 연락 혹은 문자 주시기 바랍니다.</li> 
                </ul>
            </div>

            <div>
                <h3>펀딩 현황</h3>
                <table class="table table-striped table-hover mx-auto">
                    <thead>
                        <tr>
                            <th><b>서포터</b></th>
                            <th style="width: 100px;">펀딩</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in object_list %}
                            <tr>
                                <td>{{i.user}}</td>
                                <td>{{i.cash}}</td>
                                
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
{% endblock  %}